### ISSUE TITLE
CUDA not available for numba

### ISSUE THREAD

**Issue by kentwait** [iot-salzburg/gpu-jupyter#52]
I have an Ubuntu 18.04 machine with a RTX 3090 (Driver 460.32.03 and CUDA version 11.2). I made a custom build of gpu-jupyter using the following commands:

```
git clone https://github.com/iot-salzburg/gpu-jupyter.git
cd gpu-jupyter
./generate-Dockerfile.sh
docker build -t gpu-jupyter .build/
```

My GPU, drivers, and the CUDA installation seem to be working fine based on calling `nvidia-smi` from the terminal inside Jupyter.
Also running this PyTorch check gives me `True`
```python
import torch
torch.cuda.is_available() 
```

However, numba doesn't seem to detect any CUDA devices as the following returns `False`
```python
from numba import cuda
cuda.is_available()
```
Running `numba -s` from the terminal within Jupyter detects my GPU:

```
__CUDA Information__
CUDA Device Initialized                       : True
CUDA Driver Version                           : 11020
CUDA Detect Output:
Found 1 CUDA devices
id 0     b'GeForce RTX 3090'                              [SUPPORTED]
                      compute capability: 8.6
                           pci device id: 0
                              pci bus id: 129
Summary:
        1/1 devices are supported

CUDA Librairies Test Output:
None
```

but shows the following error at the end:

```
Warning (cuda): Probing CUDA failed (device and driver present, runtime problem?)
(cuda) <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/usr/local/cuda/nvvm/lib64'
```

**Comment by ChristophSchranz** [comment]
Thanks for reporting this issue!
I have reproduced this error and it seems I solved it by updating the `cudatoolkit`.

Just run:
```bash
conda install cudatoolkit
```

I will double-check it and make the necessary changes in the Dockerfile.

**Comment by kentwait** [comment]
> Thanks for reporting this issue!
> I have reproduced this error and it seems I solved it by updating the `cudatoolkit`.
> 
> Just run:
> 
> ```shell
> conda install cudatoolkit
> ```
> 
> I will double-check it and make the necessary changes in the Dockerfile.

This also looks to be working for me.

Does this mean CUDA will be installed twice? One from the base container and the other inside the conda installation?

**Comment by ChristophSchranz** [comment]
I'm afraid it really installs conda toolkit on an existing nvidia cuda toolkit. Here is a small discussion about it: https://stackoverflow.com/questions/59529804/nvidia-cudatoolkit-vs-conda-cudatoolkit

I don't know at the moment how to unify this.

**Comment by ChristophSchranz** [comment]
Interestingly, installing Pytorch using conda instead of pip also solves this problem. The conda installation requires a cudatoolkit dependency, that may prevents overwriting a required path.

https://github.com/iot-salzburg/gpu-jupyter/blob/d4c7575d5a22319b88a9fa9c3af964dc997de62e/src/Dockerfile.gpulibs#L15-L17

Can you check if latest commit cb1b6f1aca06f405fcd47748617cb23e976fc794 also works for you?

**Comment by kentwait** [comment]
cb1b6f1 seems to solve the cuda dependency problem in numba. Thank you
