### ISSUE TITLE
dlerror: libcudnn.so.7 cudaNN is missing

### ISSUE THREAD

**Issue by titansmc** [iot-salzburg/gpu-jupyter#57]
Hi,
I am using **cschranz/gpu-jupyter:v1.1_cuda-10.1_ubuntu-18.04** (due to jupyterhub 1.1.0 ) and I see cudann is missing, how should I get it installed ?
Thanks.

```
>>> import tensorflow.compat.v1 as tf
>>> tf.test.is_gpu_available(
...     cuda_only=False, min_cuda_compute_capability=None
... )
WARNING:tensorflow:From <stdin>:2: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2021-03-18 15:04:59.245058: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-03-18 15:04:59.271631: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2399995000 Hz
2021-03-18 15:04:59.283598: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa194000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-03-18 15:04:59.283738: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-03-18 15:04:59.289403: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-03-18 15:04:59.494806: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55730caec680 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-03-18 15:04:59.494937: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0
2021-03-18 15:04:59.498194: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:86:00.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0
coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s
2021-03-18 15:04:59.499007: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-03-18 15:04:59.503812: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2021-03-18 15:04:59.508316: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2021-03-18 15:04:59.509694: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2021-03-18 15:04:59.514401: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2021-03-18 15:04:59.516827: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2021-03-18 15:04:59.517725: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory
2021-03-18 15:04:59.517783: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-03-18 15:04:59.517877: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-18 15:04:59.517931: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2021-03-18 15:04:59.517985: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
False
```

**Comment by massih10** [comment]
Same here

**Comment by mathematicalmichael** [comment]
what's the output of ` import tensorflow.compat.v1 as tf; tf.config.list_physical_devices('GPU')`?

**Comment by mathematicalmichael** [comment]
https://github.com/iot-salzburg/gpu-jupyter/issues/58#issuecomment-809696600 the fix here returns `True`. TFlow seems to want 10.1 not 10.2

**Comment by titansmc** [comment]
I have solved it like:
```
RUN apt-get update && apt-get install -y libcudnn7-dev && rm -rf /var/lib/apt/lists/*
```

**Comment by ChristophSchranz** [comment]
Thanks for reporting and solving this bug!

In newer releases as `v1.3` there should not occur this issue. Therefore, this issue is closed.
